export type Product = {
    id: string;
    title: string;
    category: string;
    sizes: (string | number)[];
    price: number;
    discountPrice?: number;
    stock: { [key: string]: number } | { default: number };
    rating?: number;
    image?: string;
    description?: string;
};

export const productList: Product[] = [
    {
        id: "p001",
        title: "Men’s Casual T-Shirt",
        category: "Clothing",
        sizes: ["S", "M", "L", "XL"],
        price: 499,
        discountPrice: 399,
        stock: { S: 10, M: 25, L: 15, XL: 7 },
        rating: 4.5,
        image: "https://picsum.photos/200?random=1",
        description: "Comfortable cotton t-shirt for everyday use",
    },
    {
        id: "p002",
        title: "Women’s Skinny Jeans",
        category: "Clothing",
        sizes: ["28", "30", "32", "34"],
        price: 1499,
        discountPrice: 1199,
        stock: { 28: 12, 30: 18, 32: 9, 34: 5 },
        rating: 4.2,
        image: "https://picsum.photos/200?random=2",
        description: "Stretchable denim jeans for a perfect fit",
    },
    {
        id: "p003",
        title: "Running Sports Shoes",
        category: "Footwear",
        sizes: [6, 7, 8, 9, 10],
        price: 2999,
        discountPrice: 2299,
        stock: { 6: 15, 7: 20, 8: 12, 9: 8, 10: 4 },
        rating: 4.8,
        image: "https://picsum.photos/200?random=3",
        description: "Breathable running shoes with long-lasting comfort",
    },

    // ---------- Clothing ----------
    {
        id: "p004",
        title: "Men’s Checkered Shirt",
        category: "Clothing",
        sizes: ["M", "L", "XL"],
        price: 899,
        discountPrice: 749,
        stock: { M: 20, L: 15, XL: 12 },
        rating: 4.1,
        image: "https://picsum.photos/200?random=4",
        description: "Classic checkered shirt with soft cotton fabric",
    },
    {
        id: "p005",
        title: "Women’s Summer Dress",
        category: "Clothing",
        sizes: ["S", "M", "L"],
        price: 1299,
        discountPrice: 999,
        stock: { S: 10, M: 18, L: 14 },
        rating: 4.6,
        image: "https://picsum.photos/200?random=5",
        description: "Lightweight floral dress for a breezy summer day",
    },
    {
        id: "p006",
        title: "Men’s Formal Pants",
        category: "Clothing",
        sizes: ["30", "32", "34", "36"],
        price: 1599,
        discountPrice: 1299,
        stock: { 30: 12, 32: 20, 34: 10, 36: 7 },
        rating: 4.3,
        image: "https://picsum.photos/200?random=6",
        description: "Slim-fit formal trousers with premium fabric",
    },
    {
        id: "p007",
        title: "Women’s Hooded Sweatshirt",
        category: "Clothing",
        sizes: ["S", "M", "L", "XL"],
        price: 999,
        discountPrice: 799,
        stock: { S: 15, M: 20, L: 18, XL: 10 },
        rating: 4.7,
        image: "https://picsum.photos/200?random=7",
        description: "Warm fleece sweatshirt perfect for winter",
    },
    {
        id: "p008",
        title: "Men’s Track Pants",
        category: "Clothing",
        sizes: ["M", "L", "XL"],
        price: 799,
        discountPrice: 649,
        stock: { M: 20, L: 15, XL: 9 },
        rating: 4.0,
        image: "https://picsum.photos/200?random=8",
        description: "Soft and stretchable track pants for workouts",
    },
    {
        id: "p009",
        title: "Women’s Leggings",
        category: "Clothing",
        sizes: ["S", "M", "L"],
        price: 599,
        discountPrice: 449,
        stock: { S: 18, M: 22, L: 16 },
        rating: 4.4,
        image: "https://picsum.photos/200?random=9",
        description: "Comfort-fit leggings made with breathable material",
    },
    {
        id: "p010",
        title: "Men’s Winter Jacket",
        category: "Clothing",
        sizes: ["M", "L", "XL"],
        price: 3499,
        discountPrice: 2799,
        stock: { M: 10, L: 15, XL: 7 },
        rating: 4.9,
        image: "https://picsum.photos/200?random=10",
        description: "Thick insulated jacket ideal for cold conditions",
    },

    // ---------- Footwear ----------
    {
        id: "p011",
        title: "Casual Sneakers",
        category: "Footwear",
        sizes: [6, 7, 8, 9, 10],
        price: 1999,
        discountPrice: 1599,
        stock: { 6: 12, 7: 22, 8: 18, 9: 10, 10: 5 },
        rating: 4.3,
        image: "https://picsum.photos/200?random=11",
        description: "Everyday sneakers with stylish design",
    },
    {
        id: "p012",
        title: "Women’s Sandals",
        category: "Footwear",
        sizes: [5, 6, 7, 8],
        price: 899,
        discountPrice: 699,
        stock: { 5: 10, 6: 18, 7: 12, 8: 8 },
        rating: 4.1,
        image: "https://picsum.photos/200?random=12",
        description: "Comfortable sandals ideal for casual outings",
    },
    {
        id: "p013",
        title: "Men’s Leather Boots",
        category: "Footwear",
        sizes: [7, 8, 9, 10],
        price: 3999,
        discountPrice: 3199,
        stock: { 7: 10, 8: 12, 9: 8, 10: 6 },
        rating: 4.8,
        image: "https://picsum.photos/200?random=13",
        description: "Premium quality leather boots with rugged sole",
    },
    {
        id: "p014",
        title: "Women’s Sports Shoes",
        category: "Footwear",
        sizes: [5, 6, 7, 8],
        price: 2499,
        discountPrice: 1999,
        stock: { 5: 14, 6: 18, 7: 10, 8: 6 },
        rating: 4.5,
        image: "https://picsum.photos/200?random=14",
        description: "Lightweight shoes suitable for gym and running",
    },
    {
        id: "p015",
        title: "Men’s Slippers",
        category: "Footwear",
        sizes: [7, 8, 9, 10],
        price: 499,
        discountPrice: 349,
        stock: { 7: 20, 8: 18, 9: 15, 10: 10 },
        rating: 4.0,
        image: "https://picsum.photos/200?random=15",
        description: "Soft and durable slippers for daily use",
    },

    // ---------- Accessories ----------
    {
        id: "p016",
        title: "Leather Wallet",
        category: "Accessories",
        sizes: ["default"],
        price: 799,
        discountPrice: 599,
        stock: { default: 50 },
        rating: 4.7,
        image: "https://picsum.photos/200?random=16",
        description: "Genuine leather wallet with multiple card slots",
    },
    {
        id: "p017",
        title: "Men’s Belt",
        category: "Accessories",
        sizes: ["M", "L", "XL"],
        price: 699,
        discountPrice: 499,
        stock: { M: 25, L: 20, XL: 15 },
        rating: 4.2,
        image: "https://picsum.photos/200?random=17",
        description: "Stylish leather belt suitable for formal wear",
    },
    {
        id: "p018",
        title: "Sports Cap",
        category: "Accessories",
        sizes: ["default"],
        price: 399,
        discountPrice: 299,
        stock: { default: 40 },
        rating: 4.3,
        image: "https://picsum.photos/200?random=18",
        description: "Breathable sports cap ideal for outdoor activities",
    },
    {
        id: "p019",
        title: "Women’s Handbag",
        category: "Accessories",
        sizes: ["default"],
        price: 2499,
        discountPrice: 1999,
        stock: { default: 20 },
        rating: 4.6,
        image: "https://picsum.photos/200?random=19",
        description: "Elegant handbag with spacious compartments",
    },
    {
        id: "p020",
        title: "Men’s Sunglasses",
        category: "Accessories",
        sizes: ["default"],
        price: 999,
        discountPrice: 749,
        stock: { default: 30 },
        rating: 4.4,
        image: "https://picsum.photos/200?random=20",
        description: "UV-protected sunglasses with modern frame design",
    },

    // ---------- Electronics ----------
    {
        id: "p021",
        title: "Wireless Earbuds",
        category: "Electronics",
        sizes: ["default"],
        price: 1999,
        discountPrice: 1499,
        stock: { default: 50 },
        rating: 4.5,
        image: "https://picsum.photos/200?random=21",
        description: "High-quality earbuds with noise cancellation",
    },
    {
        id: "p022",
        title: "Smart Watch",
        category: "Electronics",
        sizes: ["default"],
        price: 2999,
        discountPrice: 2499,
        stock: { default: 35 },
        rating: 4.3,
        image: "https://picsum.photos/200?random=22",
        description: "Smart watch with heart rate and fitness tracking",
    },
    {
        id: "p023",
        title: "Bluetooth Speaker",
        category: "Electronics",
        sizes: ["default"],
        price: 1499,
        discountPrice: 1099,
        stock: { default: 40 },
        rating: 4.4,
        image: "https://picsum.photos/200?random=23",
        description: "Portable speaker with deep bass sound",
    },
    {
        id: "p024",
        title: "Gaming Headset",
        category: "Electronics",
        sizes: ["default"],
        price: 2499,
        discountPrice: 1999,
        stock: { default: 20 },
        rating: 4.6,
        image: "https://picsum.photos/200?random=24",
        description: "Immersive surround sound headset for gaming",
    },
    {
        id: "p025",
        title: "Laptop Backpack",
        category: "Accessories",
        sizes: ["default"],
        price: 1299,
        discountPrice: 999,
        stock: { default: 25 },
        rating: 4.5,
        image: "https://picsum.photos/200?random=25",
        description: "Waterproof laptop backpack with extra padding",
    },

    // ---------- More Clothing ----------
    {
        id: "p026",
        title: "Men’s Gym Tank Top",
        category: "Clothing",
        sizes: ["S", "M", "L"],
        price: 599,
        discountPrice: 449,
        stock: { S: 15, M: 18, L: 12 },
        rating: 4.2,
        image: "https://picsum.photos/200?random=26",
        description: "Sweat-resistant tank top for gym workouts",
    },
    {
        id: "p027",
        title: "Women’s Sports Bra",
        category: "Clothing",
        sizes: ["S", "M", "L"],
        price: 899,
        discountPrice: 699,
        stock: { S: 14, M: 16, L: 10 },
        rating: 4.7,
        image: "https://picsum.photos/200?random=27",
        description: "High-support sports bra perfect for athletes",
    },
    {
        id: "p028",
        title: "Men’s Polo T-Shirt",
        category: "Clothing",
        sizes: ["M", "L", "XL"],
        price: 799,
        discountPrice: 649,
        stock: { M: 20, L: 18, XL: 12 },
        rating: 4.4,
        image: "https://picsum.photos/200?random=28",
        description: "Premium polo t-shirt with a soft collar feel",
    },
    {
        id: "p029",
        title: "Women’s Denim Jacket",
        category: "Clothing",
        sizes: ["S", "M", "L"],
        price: 1999,
        discountPrice: 1699,
        stock: { S: 8, M: 14, L: 10 },
        rating: 4.8,
        image: "https://picsum.photos/200?random=29",
        description: "Trendy denim jacket for casual outfits",
    },
    {
        id: "p030",
        title: "Men’s Kurta",
        category: "Clothing",
        sizes: ["M", "L", "XL"],
        price: 1499,
        discountPrice: 1199,
        stock: { M: 18, L: 15, XL: 10 },
        rating: 4.3,
        image: "https://picsum.photos/200?random=30",
        description: "Traditional Indian kurta with embroidery",
    },

    // ---------- More Footwear ----------
    {
        id: "p031",
        title: "Women’s Heels",
        category: "Footwear",
        sizes: [5, 6, 7, 8],
        price: 1599,
        discountPrice: 1299,
        stock: { 5: 8, 6: 12, 7: 10, 8: 6 },
        rating: 4.2,
        image: "https://picsum.photos/200?random=31",
        description: "Elegant heels perfect for parties and events",
    },
    {
        id: "p032",
        title: "Kids’ Running Shoes",
        category: "Footwear",
        sizes: [1, 2, 3, 4],
        price: 999,
        discountPrice: 799,
        stock: { 1: 10, 2: 12, 3: 14, 4: 9 },
        rating: 4.5,
        image: "https://picsum.photos/200?random=32",
        description: "Comfortable running shoes for kids",
    },
    {
        id: "p033",
        title: "Men’s Flip-Flops",
        category: "Footwear",
        sizes: [7, 8, 9, 10],
        price: 349,
        discountPrice: 249,
        stock: { 7: 15, 8: 18, 9: 20, 10: 12 },
        rating: 4.1,
        image: "https://picsum.photos/200?random=33",
        description: "Lightweight flip-flops suitable for daily wear",
    },
    {
        id: "p034",
        title: "Women’s Casual Shoes",
        category: "Footwear",
        sizes: [5, 6, 7, 8],
        price: 1299,
        discountPrice: 999,
        stock: { 5: 14, 6: 18, 7: 12, 8: 9 },
        rating: 4.3,
        image: "https://picsum.photos/200?random=34",
        description: "Comfortable casual shoes for everyday outings",
    },

    // ---------- More Accessories ----------
    {
        id: "p035",
        title: "Travel Backpack",
        category: "Accessories",
        sizes: ["default"],
        price: 1799,
        discountPrice: 1399,
        stock: { default: 25 },
        rating: 4.6,
        image: "https://picsum.photos/200?random=35",
        description: "Durable backpack with many pockets for travel",
    },
    {
        id: "p036",
        title: "Women’s Scarf",
        category: "Accessories",
        sizes: ["default"],
        price: 499,
        discountPrice: 349,
        stock: { default: 40 },
        rating: 4.4,
        image: "https://picsum.photos/200?random=36",
        description: "Soft and stylish scarf made from premium fabric",
    },
    {
        id: "p037",
        title: "Fitness Gloves",
        category: "Accessories",
        sizes: ["S", "M", "L"],
        price: 699,
        discountPrice: 549,
        stock: { S: 12, M: 18, L: 14 },
        rating: 4.5,
        image: "https://picsum.photos/200?random=37",
        description: "Anti-slip gloves ideal for gym and weightlifting",
    },
    {
        id: "p038",
        title: "Laptop Sleeve",
        category: "Accessories",
        sizes: ["default"],
        price: 899,
        discountPrice: 699,
        stock: { default: 30 },
        rating: 4.3,
        image: "https://picsum.photos/200?random=38",
        description: "Protective laptop sleeve with soft cushioning",
    },
    {
        id: "p039",
        title: "Men’s Bracelet",
        category: "Accessories",
        sizes: ["default"],
        price: 399,
        discountPrice: 299,
        stock: { default: 35 },
        rating: 4.2,
        image: "https://picsum.photos/200?random=39",
        description: "Stylish bracelet perfect for casual outfits",
    },
    {
        id: "p040",
        title: "Women’s Earrings",
        category: "Accessories",
        sizes: ["default"],
        price: 499,
        discountPrice: 379,
        stock: { default: 50 },
        rating: 4.7,
        image: "https://picsum.photos/200?random=40",
        description: "Elegant earrings that go with all outfits",
    },
    {
        id: "p041",
        title: "Men’s Cotton Shorts",
        category: "Clothing",
        sizes: ["S", "M", "L", "XL"],
        price: 899,
        discountPrice: 699,
        stock: { S: 12, M: 20, L: 15, XL: 10 },
        rating: 4.3,
        image: "https://picsum.photos/200?random=41",
        description: "Soft breathable cotton shorts for summer comfort",
    },
    {
        id: "p042",
        title: "Women’s Crop Top",
        category: "Clothing",
        sizes: ["S", "M", "L"],
        price: 799,
        discountPrice: 599,
        stock: { S: 20, M: 18, L: 14 },
        rating: 4.5,
        image: "https://picsum.photos/200?random=42",
        description: "Trendy crop top suitable for casual wear",
    },
    {
        id: "p043",
        title: "Men’s Sports Jacket",
        category: "Clothing",
        sizes: ["M", "L", "XL"],
        price: 2499,
        discountPrice: 1999,
        stock: { M: 12, L: 15, XL: 8 },
        rating: 4.7,
        image: "https://picsum.photos/200?random=43",
        description: "Lightweight jacket ideal for outdoor activities",
    },
    {
        id: "p044",
        title: "Women’s Palazzo Pants",
        category: "Clothing",
        sizes: ["S", "M", "L"],
        price: 999,
        discountPrice: 799,
        stock: { S: 16, M: 22, L: 10 },
        rating: 4.4,
        image: "https://picsum.photos/200?random=44",
        description: "Comfortable palazzo pants made from soft fabric",
    },
    {
        id: "p045",
        title: "Men’s Flip-Flops Premium",
        category: "Footwear",
        sizes: [7, 8, 9, 10],
        price: 599,
        discountPrice: 449,
        stock: { 7: 15, 8: 15, 9: 12, 10: 8 },
        rating: 4.1,
        image: "https://picsum.photos/200?random=45",
        description: "Premium EVA flip-flops for all-day comfort",
    },
    {
        id: "p046",
        title: "Women’s Running Socks (Pack of 3)",
        category: "Accessories",
        sizes: ["default"],
        price: 399,
        discountPrice: 299,
        stock: { default: 60 },
        rating: 4.6,
        image: "https://picsum.photos/200?random=46",
        description: "Breathable running socks with anti-odor technology",
    },
    {
        id: "p047",
        title: "Smart Fitness Band",
        category: "Electronics",
        sizes: ["default"],
        price: 1999,
        discountPrice: 1599,
        stock: { default: 35 },
        rating: 4.4,
        image: "https://picsum.photos/200?random=47",
        description: "Fitness band with daily activity and heart monitoring",
    },
    {
        id: "p048",
        title: "Men’s Leather Wallet Premium",
        category: "Accessories",
        sizes: ["default"],
        price: 999,
        discountPrice: 849,
        stock: { default: 45 },
        rating: 4.8,
        image: "https://picsum.photos/200?random=48",
        description: "Premium leather wallet with RFID protection",
    },
    {
        id: "p049",
        title: "Women’s Traditional Earrings",
        category: "Accessories",
        sizes: ["default"],
        price: 599,
        discountPrice: 449,
        stock: { default: 55 },
        rating: 4.7,
        image: "https://picsum.photos/200?random=49",
        description: "Beautiful traditional earrings suitable for festivals",
    },
    {
        id: "p050",
        title: "Bluetooth Neckband Earphones",
        category: "Electronics",
        sizes: ["default"],
        price: 1599,
        discountPrice: 1199,
        stock: { default: 38 },
        rating: 4.3,
        image: "https://picsum.photos/200?random=50",
        description: "Lightweight neckband earphones with long battery life",
    },
    {
        id: "p051",
        title: "Men’s Stylish Hoodie",
        category: "Clothing",
        sizes: ["M", "L", "XL"],
        price: 1299,
        discountPrice: 999,
        stock: { M: 15, L: 12, XL: 9 },
        rating: 4.5,
        image: "https://picsum.photos/200?random=51",
        description: "Warm fleece hoodie perfect for winter season",
    },
    {
        id: "p052",
        title: "Women’s Gym Leggings High-Waist",
        category: "Clothing",
        sizes: ["S", "M", "L"],
        price: 899,
        discountPrice: 699,
        stock: { S: 14, M: 18, L: 11 },
        rating: 4.8,
        image: "https://picsum.photos/200?random=52",
        description: "High-waist leggings designed for exercise and comfort",
    },
    {
        id: "p053",
        title: "Kids’ Cotton T-Shirt",
        category: "Clothing",
        sizes: ["XS", "S", "M"],
        price: 499,
        discountPrice: 349,
        stock: { XS: 10, S: 16, M: 12 },
        rating: 4.2,
        image: "https://picsum.photos/200?random=53",
        description: "Soft cotton t-shirt for kids’ daily wear",
    },
    {
        id: "p054",
        title: "Men’s Leather Loafers",
        category: "Footwear",
        sizes: [7, 8, 9, 10],
        price: 2599,
        discountPrice: 1999,
        stock: { 7: 10, 8: 14, 9: 9, 10: 7 },
        rating: 4.6,
        image: "https://picsum.photos/200?random=54",
        description: "Comfortable leather loafers for office and casual wear",
    },
    {
        id: "p055",
        title: "Women’s Stylish Sandals",
        category: "Footwear",
        sizes: [5, 6, 7, 8],
        price: 1199,
        discountPrice: 899,
        stock: { 5: 10, 6: 14, 7: 12, 8: 8 },
        rating: 4.4,
        image: "https://picsum.photos/200?random=55",
        description: "Modern design sandals suitable for all occasions",
    },
    {
        id: "p056",
        title: "Noise Cancelling Headphones",
        category: "Electronics",
        sizes: ["default"],
        price: 3999,
        discountPrice: 3299,
        stock: { default: 22 },
        rating: 4.7,
        image: "https://picsum.photos/200?random=56",
        description: "Over-ear headphones with active noise cancellation",
    },
    {
        id: "p057",
        title: "Men’s Analog Wristwatch",
        category: "Accessories",
        sizes: ["default"],
        price: 1499,
        discountPrice: 1199,
        stock: { default: 40 },
        rating: 4.4,
        image: "https://picsum.photos/200?random=57",
        description: "Stylish analog watch with leather strap",
    },
    {
        id: "p058",
        title: "Women’s Sling Bag",
        category: "Accessories",
        sizes: ["default"],
        price: 1299,
        discountPrice: 999,
        stock: { default: 28 },
        rating: 4.6,
        image: "https://picsum.photos/200?random=58",
        description: "Trendy sling bag with compact storage",
    },
    {
        id: "p059",
        title: "Gaming Mouse RGB",
        category: "Electronics",
        sizes: ["default"],
        price: 999,
        discountPrice: 799,
        stock: { default: 35 },
        rating: 4.5,
        image: "https://picsum.photos/200?random=59",
        description: "Ergonomic gaming mouse with RGB backlight",
    },
    {
        id: "p060",
        title: "LED Desk Lamp",
        category: "Electronics",
        sizes: ["default"],
        price: 799,
        discountPrice: 599,
        stock: { default: 50 },
        rating: 4.3,
        image: "https://picsum.photos/200?random=60",
        description: "Adjustable LED desk lamp for study and work",
    },
    {
    id: "p061",
    title: "Men’s Cotton Casual Shirt",
    category: "Clothing",
    sizes: ["M", "L", "XL"],
    price: 999,
    discountPrice: 799,
    stock: { M: 12, L: 18, XL: 14 },
    rating: 4.4,
    image: "https://picsum.photos/200?random=61",
    description: "Cotton casual shirt with a soft and breathable feel",
},
{
    id: "p062",
    title: "Women’s Fashion Kurti",
    category: "Clothing",
    sizes: ["S", "M", "L", "XL"],
    price: 1199,
    discountPrice: 949,
    stock: { S: 10, M: 16, L: 12, XL: 8 },
    rating: 4.6,
    image: "https://picsum.photos/200?random=62",
    description: "Elegant kurti perfect for festive and casual wear",
},
{
    id: "p063",
    title: "Portable Power Bank 10,000mAh",
    category: "Electronics",
    sizes: ["default"],
    price: 1499,
    discountPrice: 1199,
    stock: { default: 40 },
    rating: 4.5,
    image: "https://picsum.photos/200?random=63",
    description: "Compact power bank with fast charging support",
},
{
    id: "p064",
    title: "Kids’ Cotton Shorts",
    category: "Clothing",
    sizes: ["S", "M", "L"],
    price: 599,
    discountPrice: 449,
    stock: { S: 12, M: 18, L: 10 },
    rating: 4.3,
    image: "https://picsum.photos/200?random=64",
    description: "Soft and comfortable shorts for kids’ daily wear",
},
{
    id: "p065",
    title: "Men’s Running Shoes",
    category: "Footwear",
    sizes: [6, 7, 8, 9, 10],
    price: 2499,
    discountPrice: 1999,
    stock: { 6: 15, 7: 10, 8: 12, 9: 8, 10: 5 },
    rating: 4.7,
    image: "https://picsum.photos/200?random=65",
    description: "Durable running shoes with superior grip",
},
{
    id: "p066",
    title: "Women’s Party Handbag",
    category: "Accessories",
    sizes: ["default"],
    price: 1599,
    discountPrice: 1299,
    stock: { default: 20 },
    rating: 4.5,
    image: "https://picsum.photos/200?random=66",
    description: "Stylish handbag perfect for parties and events",
},



];
// ... add the rest of your products here (up to 40)

